# Generated by Django 6.0.3 on 2026-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type')},
        ),
    ]
